### ISSUE TITLE
Production build error when running with `node:crypto`

### ISSUE THREAD

**Issue by fullyherge** [datocms/nextjs-with-cache-tags-starter#2]
Webpack throws below error when building for production with `npm run build`. I have worked around this by following the recommendation [here](https://nextjs.org/docs/messages/node-module-in-edge-runtime) - using the WebCrypto API instead. 

Unsure if I may be missing something! Thanks for a good example project, otherwise.

<details>

  <summary>
  Error log
  </summary>

  ```bash
  > next build
  
    ▲ Next.js 14.2.4
    - Environments: .env.local
  
     Creating an optimized production build ...
  Failed to compile.
  
  node:crypto
  Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "node:" URIs.
      at /Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:401757
      at Hook.eval [as callAsync] (eval at create (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:13:28858), <anonymous>:6:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:13:26012)
      at Object.processResource (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:401682)
      at processResource (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
      at iteratePitchingLoaders (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
      at runLoaders (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
      at NormalModule._doBuild (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:401544)
      at NormalModule.build (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:403572)
      at /Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:82055
      at NormalModule.needBuild (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:407670)
      at Compilation._buildModule (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:81772)
      at /Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:1332897
      at Hook.eval [as callAsync] (eval at create (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:13:28858), <anonymous>:6:1)
      at AsyncQueue._startProcessing (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:1332768)
      at AsyncQueue._ensureProcessing (/Users/herge/Fully/projects/forge/node_modules/next/dist/compiled/webpack/bundle5.js:28:1332617)
      at process.processImmediate (node:internal/timers:476:21)
  
  Import trace for requested module:
  node:crypto
  ./src/lib/cms/dato/fetch-content.ts
  ```

  </details>
  
  <details>

  <summary>
  Updated generateQueryId function
  </summary>

  ```ts
  async function generateQueryId<
    Result = unknown,
    Variables = Record<string, unknown>,
  >(query: TypedDocumentNode<Result, Variables>, variables?: Variables) {
    const encoder = new TextEncoder();
  
    // Combine the input data
    const dataToHash = print(query) + (JSON.stringify(variables) || "");
  
    // Encode the combined data as Uint8Array
    const data = encoder.encode(dataToHash);
  
    // Hash the data using SHA-1
    const hashBuffer = await crypto.subtle.digest("SHA-1", data);
  
    // Convert the hash buffer to a hexadecimal string
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
  
    return hashHex;
  }
  ```

</details>

**Comment by fullyherge** [comment]
Changing from
`import { createHash } from "node:crypto"`
to
`import { createHash } from "crypto"` also seems to work....

**Comment by stefanoverna** [comment]
Thank you @fullyherge!
